spring:
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect

    show-sql: true

    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/rgr_back
    username: postgres
    password: 1

  mail:
    host: smtp.yandex.ru
    username: the.secretshop@yandex.ru
    password: ibs2022rgr
    port: 465
    protocol: stmps

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

mail:
  debug: true


photo:
  url: hello

app:
  url: https://8134-128-69-16-212.eu.ngrok.io

server:
  port: 8080